### ISSUE TITLE
Unable to Connect to Local Plex Server

### ISSUE THREAD

**Issue by timlich** [edde746/plezy#16]
After investigating with both the iOS and Windows apps, local servers (without remote access enabled) seem to be unable to connect.

I have narrowed this down to the connection test that is run using the URI provided by Plex. In plex_auth_service.dart the function "[findBestWorkingConnection](https://github.com/edde746/plezy/blob/4246d7689d91e10fd09b2176a05b0a39e5fb424f/lib/services/plex_auth_service.dart#L338)" uses the URI. This function find the "best" connection and then saves it to the "PlexConnection" variable. 

This results in the [error on line 112](https://github.com/edde746/plezy/blob/4246d7689d91e10fd09b2176a05b0a39e5fb424f/lib/services/server_connection_service.dart#L112) "No working connections found for this server"

The URI for servers without remote access cannot be access because Plex doesn't have any connection to the server. Normally they use the plex.direct domain name to point to the server but if there are no open ports on the router then the connection will fail. The easiest solution would probably be to use the address and port if the server connection is local (or maybe test both address and URI).

Basically this functions the same as a web browser but the native Plex app can make direct connections to local servers using private IP addresses.

Local connection from https://clients.plex.tv/api/v2
`<connection protocol="https" address="10.10.0.5" port="32400" uri="https://10-10-0-5.<serverid>.plex.direct:32400" local="1" relay="0" IPv6="0"/>`
address is reachable but the URI doesn't work because there are no ports open

Remote connection from https://clients.plex.tv/api/v2
`<connection protocol="https" address="public IP address" port="32400" uri="https://<x-x-x-x publicIP>.<serverid>.plex.direct:32400" local="0" relay="0" IPv6="0"/>`

TL;DR Please implement truly local connections rather than relying on plex.direct connections.

P.S. Great app 👍

**Comment by edde746** [comment]
Thank you for the detailed issue! Will look into this ASAP.

**Comment by edde746** [comment]
Should be fixed. Are you able to download the latest version (not on iOS yet) and test?

**Comment by Dragonfyre08** [comment]
I am also experiencing this issue with both the Windows and Android apps on V1.4.0

**Comment by timlich** [comment]
@edde746 I am still having this issue on V1.4.0. I believe the issue is related to the SSL certs now. If you load https://10.10.0.5:32400 this will tell you the cert isn't trusted because it belongs to plex.direct. So there are two options I'm looking at right now. 

1) Configure Dio to trust plex.direct certs
2) Send the plex.direct hostname with the request. In curl it would look like 
"curl --resolve 10-10-0-5.serverID.plex.direct:32400:10.10.0.5 https://10-10-0-5.serverID.plex.direct:32400"
This would request 10.10.0.5:32400 and send the server's hostname so the SSL cert is trusted.
I'm new to flutter so not sure how to make this work but I will experiment later today

3) Use http for local connections (not great)

**Comment by timlich** [comment]
@edde746 I'm not a flutter dev so I'm a bit out of my league here. I added 

    (_dio.httpClientAdapter as IOHttpClientAdapter).createHttpClient = () {
      final client = HttpClient();
      client.badCertificateCallback = (cert, host, port) => true;
      return client;
    };

at line [here](https://github.com/edde746/plezy/blob/7fcf79045b65090d3c0b1f871c7bbb1df5e85ac6/lib/client/plex_client.dart#L48) and [here](https://github.com/edde746/plezy/blob/7fcf79045b65090d3c0b1f871c7bbb1df5e85ac6/lib/client/plex_client.dart#L98) and the result was the ability to connect to local servers. This code bypasses certs (because the host and domain name don't match when making the request). It does have the odd effect of preventing images from loading and haven't figured out why yet.

also had to add 

import 'dart:io';
import 'package:dio/io.dart';

**Comment by edde746** [comment]
@timlich Could you try one of these builds and see if that fixes the issue? https://github.com/edde746/plezy/actions/runs/19123340009 (scroll to the bottom to the "Artifacts" section)

**Comment by timlich** [comment]
@edde746 That seems to have resolved the issue. All HTTP requests succeed. I see that you went with the HTTP option for local connections. Any idea how to get around the cert issue so SSL could be used? Its fine if this is all you want to do just curious.

**Comment by edde746** [comment]
Dio isn't used for all networking, like you said, images break, and so would playback (since libmpv has it's own networking too), this is the easiest solution and I don't see too much of a downside. Closing this for now as it's working.
