### ISSUE TITLE
[Defect] Hidden/unpinned libraries still populate home screen rows

### ISSUE THREAD

**Issue by ALittleCremeFraiche** [edde746/plezy#88]
Wow - this is looking great already! I notice that the home screen is populated with every single library on the server, even unpinned/hidden ones. Replicated on Windows and Android

**Comment by edde746** [comment]
Fixed with https://github.com/edde746/plezy/commit/a878a9a5122c415954914d1aafe6c3fa479f83d3

**Comment by ALittleCremeFraiche** [comment]
Oh yes I see - my apologies!

**Comment by nielsvdp** [comment]
I'm running Plezy 1.7.1 and it's still showing content from hidden libraries on the home screen. I tried logging out and removing all data from the app but that had no effect.

I have a Comedy library that I rarely watch stuff from on my phone and now my home screen has 6 categories for this library before all others since it's alphabetically first.
